# Generated by Django 5.0.1 on 2025-11-15 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, help_text='Email único do usuário', max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(help_text='Nome completo do usuário', max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o usuário está ativo no sistema', verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica se o usuário pode acessar o admin', verbose_name='Staff')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora de criação do usuário', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização', verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='Os grupos aos quais este usuário pertence.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='custom_user_permissions_set', related_query_name='user', to='auth.permission', verbose_name='permissões do usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
